posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

pyplane/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('profiles/', include('profiles.urls', namespace='profile')),
    path('posts/', include('posts.urls', namespace='post')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Account



class Post(models.Model):
    author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='author_posts')
    content = models.TextField()
    image = models.ImageField(upload_to='', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])], blank=True)
    liked = models.ManyToManyField(Account, blank=True, related_name='Likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    def num_likes(self):
        return self.liked.all().count()

    def num_comments(self):
        return self.comment_set.all().count()

    

    class Meta:
        ordering = ('-created'),



class Comment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body)



LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.post} - {self.value}"

posts/forms.py
from django import forms
from .models import *

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ('content', 'image')


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput
            (attrs={'placeholder': 'Add a comment..', 'class': 'form-conrol'}))
    class Meta:
        model = Comment
        fields = ('body', )

posts/views.py
from django.shortcuts import render, redirect
from .models import *
from profiles.models import Account
from .forms import PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages


def post_comment_create_and_list_view(request):
    qs = Post.objects.all()
    account = Account.objects.get(user=request.user)

    post_form = PostModelForm()
    comment_form = CommentModelForm()
    post_add = False

    if 'submit_post_form' in request.POST:
        print(request.POST)
        post_form = PostModelForm(request.POST, request.FILES)
        account = Account.objects.get(user=request.user)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = account
            instance.save()

            post_form = PostModelForm()
            post_add = True
            return redirect('posts:main-post-view')

    if 'submit_comment_form' in request.POST:
        comment_form = CommentModelForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = account
            instance.post = Post.objects.get(id = request.POST.get('post_id'))
            instance.save()

            comment_form = CommentModelForm()
            return redirect('posts:main-post-view')



    context = {
        'qs': qs,
        'account': account,
        'post_form': post_form,
        'comment_form': comment_form,
        'post_added': post_add,
    }
    return render(request, 'posts/main.html', context)


def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        account = Account.objects.get(user=user)

        if account in post_obj.liked.all():
            post_obj.liked.remove(account)
        else:
            post_obj.liked.add(account)

        like, created = Like.objects.get_or_create(user=account, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value= 'Unlike'
            else:
                like.value='Like'
        else:
            like.value = 'Like'

        post_obj.save()
        like.save()

        return redirect('posts:main-post-view')



class PostDeleteView(DeleteView):
    model = Post
    template_name = 'posts/confirm_delete.html'
    success_url = reverse_lazy('posts:main-post-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        if not post.author.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the post inorder to delete it')
        return post


class PostUpdateView(UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main-post-view')

    def form_valid(self, form):
        account = Account.objects.get(user=self.request.user)
        if form.instance.author == account:
            return super().form_valid(form)
        else:
            form.add_error(None, 'You need to be an author to update the post')
            return super().form_invalid(form)

posts/templates/posts/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Delete Post
{% endblock title %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if 'warning' in message.tags %}
        <div class='btn-outline-danger'>
            <div class='header'>
                {{ message }}
            </div>
        </div>
        {% endif %}
    {% endfor %}
{% endif %}


{% if not messages %}
<div class="card">
    <h3>Delete Post</h3>
    <form action="" method="POST">
        {% csrf_token %}
        <p><b>Are you sure you want to delete </b> {{ post.content }}?</p>
        <button type='submit' class="btn-danger">Delete</button>
    </form>
</div>
{% endif %}

{% endblock content %}

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock title %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">

            <div class="col-lg-6" >
                <div style="border: 1px solid black;padding: 1rem;">
                    {% if post_added %}
                        <div class="btn btn-outline-success">Post added</div>
                    {% endif %}
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ post_form.as_p }}
                        <button type="submit" class="btn btn-primary"submit_post_form">Send Post</button>
                    </form>
                </div>
            </div><br><br>

            <div class="col-lg-6">
                <div>
                    
                    {% for post in qs %}
                    <div class="card" style="margin-bottom: 2rem;padding: 1rem;">
                    <div>
                        {% ifequal request.user post.author.user %}
                            <div style="float: right;">
                                <a href="{% url 'posts:post-update' post.id %}"><button class="btn-outline-primary">Update</button></a>
                                <a href="{% url 'posts:post-delete' post.id %}"><button class="btn-outline-danger">Delete</button></a>
                            </div>
                        {% endifequal %}
                        <p> {{ post.content }} </p>
                        
                        <img src="{{ post.image.url }}" class="img img-responsive" style="width:100%;" />
                        <small>{{post.created | timesince}} ago</small>
                        <form action="{% url 'posts:like-post-view' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{ post.id }}" name="post_id" />
                            <button class="btn-outline-primary" style="border: none;" type="submit">
                                {% if account not in post.liked.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                            &nbsp; {{post.num_likes}}
                        </form>
                        
                    </div>
                    <div>
                        <ul>
                        {% if post.comment_set.all %}
                            {% for comment in post.comment_set.all %}
                            <li><small>{{ comment.body }}</small></li>
                            {% endfor %}
                        {% endif %}
                       </ul>
                        
                    </div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name='post_id' value="{{ post.id }}" />
                        {{ comment_form }}
                        <button type="submit" class="btn-primary" name="submit_comment_form">Comment</button>
                    </form>
                </div>
                    {% endfor %}
                    
                </div>

            </div>

            
        </div>
    </div>
</div>








{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
Update
{% endblock title %}

{% block content %}
<div class="card">
    <h3>Update Post</h3>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary mt-5">Update</button>
    </form>
</div>
{% endblock content %}